export {default as solar__skyscraper} from "./solar-skyscraper.png";
export {default as company__photo} from "./company_photo.jpeg";
export {default as panel} from "./panel.jpeg";
export {default as turbine} from "./turbine.jpeg";
export {default as batteries} from "./batteries.jpeg";
export {default as member1 } from "./member-1.jpeg";
export {default as member2 } from "./member-2.jpeg";
export {default as member3 } from "./member-3.jpeg";
export {default as member4 } from "./member-4.jpeg";
export {default as profile1} from "./profile-1.png";
export {default as profile2} from "./profile-2.jpeg";
export {default as profile3} from "./profile-3.jpeg";
export {default as profile4} from "./profile-4.jpeg";
export {default as profile5} from "./profile-5.jpg";
export {default as profile6} from "./profile-6.png";
export {default as inspection} from "./inspection.jpg";
export {default as electrical} from "./electrical.png";
export {default as mechanical} from "./mechanical.jpg";
export {default as solar_1} from "./solar-1.png";
export {default as solar_2} from "./solar-2.png";
export {default as light_1} from "./light-1.png";
export {default as light_2} from "./light-2.png";
export {default as light_3} from "./light-3.png";
export {default as hvac} from "./HVAC.png";
export {default as elevator} from "./elevator.png";
